name: Build Windows

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies with choco and vcpkg
        run: |
          choco install -y wget pkgconfiglite --no-progress
          C:\vcpkg\vcpkg.exe install cairo[core]:x64-windows-static gtk:x64-windows-static
      - name: Build Scarab
        run: |
          cmake -E make_directory build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CXX_FLAGS="/O2 /arch:AVX /fp:fast /EHsc"
          cmake --build . --config Release
        shell: cmd
      - name: Clean up distribution folder
        run: |
          cd build
          Remove-Item .\Release\*.exp -Force
          Remove-Item .\Release\*.lib
          Remove-Item .\Release\*.runsettings
      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/Release
          name: ScarabWin64
